routes/web.php
<?php

// panggil controller Siswa
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\KecamatanController;
use App\Models\Kecamatan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



// route kota/kabupaten
Route::resource('kota', KotaController::class);
Auth::routes();

// route kecamatan
Route::resource('kecamatan', KecamatanController::class);
Auth::routes();

// route siswa
Route::resource('siswa', SiswaController::class);
Auth::routes();

//dinamic
Route::get('getkel/{id}', function ($id) {
    $kecamatan = Kecamatan::where('kota_id', $id)->get();
    return response()->json($kecamatan);
});

app/Models/Siswa.php
<?php

namespace App\Models;

use App\Models\Kecamatan;
use App\Models\Kota;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;
    // public $fillable = ['nama','hari','tanggal','jam','kota','no_lab','kegiatan','tanggal_berakhir','keterangan'];
    // membuat fitur created_at(kapan data dibuat) & updated_at (kapan data diedit)
    // aktif
    public $guarded = ['id'];

    public function kota()
    {
        return $this->belongsTo(Kota::class, 'kota_id');
    }
    public function kecamatan()
    {
        return $this->belongsTo(Kecamatan::class, 'kecamatan_id');
    }

}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use App\Models\Kecamatan;
use App\Models\Kota;
use Illuminate\Http\Request;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $kota = Kota::all();
        $siswa = Siswa::with('kecamatan', 'kota')->latest()->get();

        // $siswa = Siswa::all();
        return view('siswa.index', compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kecamatans = Kecamatan::all();
        $kotas = Kota::all();
        return view('siswa.create', compact('kecamatans', 'kotas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama' => 'required',
            'kota_id' => 'required',
            'kecamatan_id' => 'required',
            'alamat' => 'required',
        ]);
        $siswa = new Siswa();
        $siswa->nama = $request->nama;
        $siswa->kecamatan_id = $request->kecamatan_id;
        $siswa->kota_id = $request->kota_id;
        $siswa->alamat = $request->alamat;

      

        $siswa->save();
        return redirect()->route('siswa.index')
            ->with('success', 'Data berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $siswa = Siswa::findOrFail($id);
        return view('siswa.show', compact('siswa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);
        $kecamatans = Kecamatan::where('kota_id', $siswa->kota_id)->get();
        $kotas = Kota::all();
        return view('siswa.edit', compact('siswa', 'kecamatans', 'kotas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'kota_id' => 'required',
            'nama' => 'required',
            'kecamatan_id' => 'required',
            'alamat' => 'required',
        ]);

        $siswa = Siswa::findOrFail($id);
        $siswa->nama = $request->nama;
        $siswa->kecamatan_id = $request->kecamatan_id;
        $siswa->kota_id = $request->kota_id;
        $siswa->alamat = $request->alamat;
        $siswa->save();
        return redirect()->route('siswa.index')
            ->with('success', 'Data berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $siswa = Siswa::findOrFail($id);
        $siswa->delete();
        return redirect()->route('siswa.index')
            ->with('success', 'Data berhasil dihapus!');
    }

}

resources/views/siswa/create.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Siswa
                    </div>
                    <div class="card-body">
                        <form action="{{ route('siswa.store') }}" method="post">
                            @csrf
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="">Nama</label>
                                <div class="col-sm-10">
                                    <div class="input-group input-group-merge">
                                <input type="text" class="form-control  @error('nama') is-invalid @enderror"
                                    name="nama">
                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Kota/Kabupaten</label>
                                <div class="col-sm-10">
                                    <div class="input-group input-group-merge">
                                <select name="kota_id"  id="kota"
                                 class="form-control @error('kota_id') is-invalid @enderror">
                                    @foreach ($kotas as $kota)
                                    <option value="" hidden>pilih Kota/Kabupaten
                                    <option value="{{ $kota->id }}">{{ $kota->kota }}
                                    </option>
                                    @endforeach
                                </select>
                                @error('kota_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            </div>
                            </div>
                         
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Kecamatan</label>
                                <div class="col-sm-10">
                                    <div class="input-group input-group-merge">
                                <select name="kecamatan_id" id="kecamatan" 
                                class="form-control @error('kecamatan_id') is-invalid @enderror">
                                    {{-- @foreach ($kel_labs as $kecamatan) --}}
                                    <option value="" hidden>Pilih Kota/Kabupaten dulu
                                    </option>
                                    {{-- @endforeach --}}
                                </select>
                                @error('kecamatan_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="basic-icon-default-fullname">Alamat</label>
                                <div class="col-sm-10">
                                    <div class="input-group input-group-merge">
                                <textarea class="form-control  @error('alamat') is-invalid @enderror" name="alamat"></textarea>
                                @error('alamat')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            </div>
                            </div>
                          
                            <div class="row justify-content-end">
                                <div class="col-sm-10">
                                  <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                              </div>
                              
                        
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> 
    <script>
        $(document).ready(function() {
            $('#kota').on('change', function() {
                var kota_id = $(this).val();
                if (kota_id) {
                    $.ajax({
                        url: '/getkel/' + kota_id,
                        type: "GET",
                        data: {
                            "_token": "{{ csrf_token() }}"
                        },
                        dataType: "json",
                        success: function(data) {
                            if (data) {
                                $('#kecamatan').empty();
                                $('#kecamatan').append(
                                    '<option hidden>Pilih Kota/Kabupaten</option>');
                                $.each(data, function(key, kecamatan) {
                                    $('select[name="kecamatan_id"]').append(
                                        '<option value="' + kecamatan.id + '">' +
                                        kecamatan.kecamatan + '</option>');
                                });
                            } else {
                                $('#kecamatan').empty();
                            }
                        }
                    });
                } else {
                    $('#kecamatan').empty();
                }
            });
        });
    </script>

resources/views/siswa/edit.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts._flash')
                <div class="card border-secondary">
                    <div class="card-header mb-3">Data Siswa</div>

                    <div class="card-body">
                        <form action="{{ route('siswa.update', $siswa->id) }}" method="post">
                            @method('put')
                            @csrf
                            <div class="mb-3">
                                <label for="">Nama</label>
                                <input type="text" name="nama"
                                    class="form-control @error('nama') is-invalid @enderror" value="{{ $siswa->nama }}">
                                </input>
                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                          
                           
                            <div class="mb-1">
                                <label for="">Kota/Kabupaten</label>
                                <select name="kota_id" id="kota"
                                    class="form-control @error('kota_id') is-invalid @enderror">
                                    @foreach ($kotas as $kota)
                                        <option value="" hidden>pilih Lantai
                                        <option value="{{ $kota->id }}">{{ $kota->kota }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('kota_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="mb-1">
                                <label for="">Kecamatan</label>
                                <select name="kecamatan_id" id="kecamatan"
                                    class="form-control @error('kecamatan_id') is-invalid @enderror">
                                    {{-- @foreach ($kel_labs as $kecamatan) --}}
                                    <option value="" hidden>Pilih Kota/Kabupaten lebih dulu
                                    </option>
                                    {{-- @endforeach --}}
                                </select>
                                @error('kecamatan_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label for="">Alamat</label>
                                <input type="text" name="alamat"
                                    class="form-control @error('alamat') is-invalid @enderror" value="{{ $siswa->alamat }}">
                                </input>
                                @error('alamat')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                           
                                    <button class="btn btn-primary" type="submit">Kirim</button>
                                    {{-- <a href="{{ route('siswa.index') }}" class="btn btn-danger"
                                        type="submit">Kembali</a>
                                </div> --}}
                                {{-- </div>
                        <div class="mb-3">
                            <div class="d-grid gap-2">

                            </div>
                        </div> --}}
                        </form>
                   
            </div>
        </div>
    </div>
@endsection

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
        $('#kota').on('change', function() {
            var kota_id = $(this).val();
            if (kota_id) {
                $.ajax({
                    url: '/getkel/' + kota_id,
                    type: "GET",
                    data: {
                        "_token": "{{ csrf_token() }}"
                    },
                    dataType: "json",
                    success: function(data) {
                        if (data) {
                            $('#kecamatan').empty();
                            $('#kecamatan').append(
                                '<option hidden>Pilih Kecamatan</option>');
                            $.each(data, function(key, kecamatan) {
                                $('select[name="kecamatan_id"]').append(
                                    '<option value="' + kecamatan.id + '">' +
                                    kecamatan.kecamatan + '</option>');
                            });
                        } else {
                            $('#kecamatan').empty();
                        }
                    }
                });
            } else {
                $('#kecamatan').empty();
            }
        });
    });
</script>

resources/views/siswa/index.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Siswa
                        <a href="{{ route('siswa.create') }}" class="btn btn-sm btn-primary" style="float: right">
                            Tambah Data
                        </a>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table align-middle" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Kota/Kabupaten</th>
                                        <th>Kecamatan</th>
                                        <th>Alamat</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach ($siswa as $data)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td>{{ $data->nama }}</td>
                                            <td>{{ $data->kota->kota }}</td>
                                            <td>{{ $data->kecamatan->kecamatan }}</td>
                                            <td>{{ $data->alamat }}</td>
                                            <td>
                                                <form action="{{ route('siswa.destroy', $data->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('siswa.edit', $data->id) }}" class="btn btn-sm btn-outline-success ">
                                                        <i class='bx bx-edit'></i>
                                                    </a> |
                                                    <a href="{{ route('siswa.show', $data->id) }}" class="btn btn-sm btn-outline-warning ">
                                                        <i class='bx bx-show-alt'></i>
                                                    </a> |
                                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Apakah Anda Yakin?')">
                                                        <i class='bx bx-trash'></i>
                                                    </button>
                                                    
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/siswa/show.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Data Siswa
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label class="form-label">Nama Siswa</label>
                            <input type="text" class="form-control " name="nama" value="{{ $siswa->nama }}" readonly>
                            <br>
                            <div class="mb-3">
                                <label class="form-label">Kota/Kabupaten</label>
                                <input type="text" class="form-control" name="kota_id" value="{{ $siswa->kota->kota }}" readonly>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Kecamatan</label>
                                <input type="text" class="form-control" name="kecamatan_id" value="{{ $siswa->kecamatan->kecamatan }}" readonly>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Alamat</label>
                                <input type="text" class="form-control" name="alamat" value="{{ $siswa->alamat }}" readonly>
                            </div>
                     
                          
                                <a href="{{ route('siswa.index') }}" class="btn btn-danger" type="submit">Kembali</a>
                           
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection