routes/web.php
<?php

// panggil controller Siswa
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\KecamatanController;
use App\Models\Kecamatan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



// route kota/kabupaten
Route::resource('kota', KotaController::class);
Auth::routes();

// route kecamatan
Route::resource('kecamatan', KecamatanController::class);
Auth::routes();

// route siswa
Route::resource('siswa', SiswaController::class);
Auth::routes();

//dinamic
Route::get('getkel/{id}', function ($id) {
    $kecamatan = Kecamatan::where('kota_id', $id)->get();
    return response()->json($kecamatan);
});

app/Models/Kecamatan.php
<?php

namespace App\Models;

use App\Models\Siswa;
use App\Models\kota;
use Illuminate\Database\Eloquent\Factories\HasFactory;
// use App\Models\Kel_lab;
use Illuminate\Database\Eloquent\Model;

class Kecamatan extends Model
{
    use HasFactory;
    // public $fillable = ['no_lab', 'kondisi'];

    // membuat fitur created_at(kapan data dibuat) & updated_at (kapan data diedit)
    // aktif
    public $guarded = [];
    public $timestamps = true;
    public $table = 'kecamatans';

    public function kota()
    {
        return $this->belongsTo(kota::class, 'kota_id');
    }
    public function Siswa()
    {
        return $this->hasMany(Siswa::class, 'id');
    }

}

app/Http/Controllers/KecamatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kecamatan;
use App\Models\Kota;
// use App\Models\Jad_lab;
use Illuminate\Http\Request;

class KecamatanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      
        $kota = Kota::all();
        $kecamatan = Kecamatan::all();
        return view('kecamatan.index', compact('kecamatan', 'kota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kecamatans = Kecamatan::all();
        $kecamatans = Kota::all();
        return view('kecamatan.create', compact('kecamatans'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'kota_id' => 'required',
            'kecamatan' => 'required',
          
        ]);
        $kecamatan = new Kecamatan();
        $kecamatan->kota_id = $request->kota_id;
        $kecamatan->kecamatan = $request->kecamatan;
      
        $kecamatan->save();
        return redirect()->route('kecamatan.index')
            ->with('success', 'Data berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        return view('kecamatan.show', compact('kecamatan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kota = Kota::all();
        return view('kecamatan.edit', compact('kecamatan', 'kota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validated = $request->validate([
            'kota_id' => 'required',
            'kecamatan' => 'required',
          
        ]);

        $kecamatan = Kecamatan::findOrFail($id);
        $kecamatan->kota_id = $request->kota_id;
        $kecamatan->kecamatan = $request->kecamatan;
      
        $kecamatan->save();
        return redirect()->route('kecamatan.index')
            ->with('success', 'Data berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kecamatan = Kecamatan::findOrFail($id);
        $kecamatan->delete();
        return redirect()->route('kecamatan.index')
            ->with('success', 'Data berhasil dihapus!');
    }
    public function getKecamatan($id)
    {
        $kecamatans = Kecamatan::where('kota_id', $id)->get();
        return response()->json($kecamatans);
    }
}

resources/views/kecamatan/create.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kecamatan
                    </div>
                    <div class="card-body">
                        <form action="{{ route('kecamatan.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Kecamatan</label>
                                <input type="text" class="form-control  @error('kecamatan') is-invalid @enderror"
                                    name="kecamatan">
                                @error('kecamatan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="mb-1">
                                <label for="">Kota/Kabupaten</label>
                                <select name="kota_id" id="kota"
                                    class="form-control @error('kota_id') is-invalid @enderror">
                                    @foreach ($kecamatans as $kota)
                                        <option value="" hidden>Pilih Kota/Kabupaten
                                        <option value="{{ $kota->id }}">{{ $kota->kota }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('kota_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                           
                          <br>
                                    <button class="btn btn-primary" type="submit">Save</button>
                             
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kecamatan/edit.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kecamatan
                    </div>
                    <div class="card-body">
                        <form action="{{ route('kecamatan.update', $kecamatan->id) }}" method="post">
                            @csrf
                            @method('put')
                            <div class="mb-3">
                                <label class="form-label">Kecamatan</label>
                                <input type="text" class="form-control  @error('kecamatan') is-invalid @enderror"
                                    name="kecamatan" value="{{ $kecamatan->kecamatan }}">
                                @error('kecamatan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="mb-1">
                                <label for="">Kota/Kabupaten</label>
                                <select name="kota_id" class="form-control @error('kota_id') is-invalid @enderror">
                                    @foreach ($kota as $kota)
                                        <option value="{{ $kota->id }}">{{ $kota->kota }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('kota_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                  
                          <br>
                                    <button class="btn btn-primary" type="submit">Save</button>
                              
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kecamatan/index.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kecamatan
                        <a href="{{ route('kecamatan.create') }}" class="btn btn-sm btn-primary" style="float: right">
                            Tambah Data
                        </a>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table align-middle" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Kecamatan</th>
                                        <th>Kota/Kabupaten</th>
                                      
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach ($kecamatan as $data)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td>{{ $data->kecamatan }}</td>
                                              <td>{{ $data->kota->kota }}</td>
                                          
                                            <td>
                                                <form action="{{ route('kecamatan.destroy', $data->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('kecamatan.edit', $data->id) }}" class="btn btn-sm btn-outline-success ">
                                                        <i class='bx bx-edit'></i>
                                                    </a> |
                                                    <a href="{{ route('kecamatan.show', $data->id) }}" class="btn btn-sm btn-outline-warning ">
                                                        <i class='bx bx-show-alt'></i>
                                                    </a> |
                                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Apakah Anda Yakin?')">
                                                        <i class='bx bx-trash'></i>
                                                    </button>
                                                    
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kecamatan/show.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Data Kecamatan
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label class="form-label">Kecamatan</label>
                            <input type="text" class="form-control " name="kecamatan" value="{{ $kecamatan->kecamatan }}" readonly>
                        <br>
                            <div class="mb-3">
                                <label class="form-label">Kota/Kabupaten</label>
                                <input type="text" class="form-control" name="kota_id" value="{{ $kecamatan->kota->kota }}" readonly>
                            </div>
                      
                                <a href="{{ route('kecamatan.index') }}" class="btn btn-primary" type="submit">Kembali</a>
                          
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection