routes/web.php
<?php

// panggil controller Siswa
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\KecamatanController;
use App\Models\Kecamatan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



// route kota/kabupaten
Route::resource('kota', KotaController::class);
Auth::routes();

// route kecamatan
Route::resource('kecamatan', KecamatanController::class);
Auth::routes();

// route siswa
Route::resource('siswa', SiswaController::class);
Auth::routes();

//dinamic
Route::get('getkel/{id}', function ($id) {
    $kecamatan = Kecamatan::where('kota_id', $id)->get();
    return response()->json($kecamatan);
});

app/Models/Kota.php
<?php

namespace App\Models;

use App\Models\Siswa;
use App\Models\Kecamatan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kota extends Model
{
    use HasFactory;
   
    protected $table = 'kotas';
    public function kecamatan()
    {
        return $this->hasMany(Kecamatan::class);
    }
    public function Siswa()
    {
        return $this->hasMany(Siswa::class, 'id_siswas');
    }
}

app/Http/Controllers/KotaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kota;
use Illuminate\Http\Request;

class KotaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //menampilkan semua data dari model Kota
        $kota = Kota::all();
        return view('kota.index', compact('kota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('kota.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi
        $validated = $request->validate([
            'kota' => 'required',
           
        ]);

        $kota = new Kota();
        $kota->kota = $request->kota;
      
        $kota->save();
        return redirect()->route('kota.index')
            ->with('success', 'Data berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kota = Kota::findOrFail($id);
        return view('kota.show', compact('kota'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kota = Kota::findOrFail($id);
        return view('kota.edit', compact('kota'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validasi
        $validated = $request->validate([
            'kota' => 'required',
           
        ]);

        $kota = Kota::findOrFail($id);
        $kota->kota = $request->kota;
      
        $kota->save();
        return redirect()->route('kota.index')
            ->with('success', 'Data berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kota = Kota::findOrFail($id);
        $kota->delete();
        return redirect()->route('kota.index')
            ->with('success', 'Data berhasil dihapus!');
    }
}

resources/views/kota/create.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kota/Kabupaten
                    </div>
                    <div class="card-body">
                        <form action="{{ route('kota.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Kota/Kabupaten</label>
                                <input type="text" class="form-control  @error('kota') is-invalid @enderror"
                                    name="kota">
                                @error('kota')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                           
                          
                                    <button class="btn btn-primary" type="submit">Save</button>
                              
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kota/edit.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kota/Kabupaten
                    </div>
                    <div class="card-body">
                        <form action="{{ route('kota.update', $kota->id) }}" method="post">
                            @csrf
                            @method('put')
                            <div class="mb-3">
                                <label class="form-label">Kota Kabupaten</label>
                                <input type="text" class="form-control  @error('kota') is-invalid @enderror"
                                    name="kota" value="{{ $kota->kota }}">
                                @error('kota')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                  
                      
                                    <button class="btn btn-primary" type="submit">Save</button>
                               
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kota/index.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('layouts/_flash')
                <div class="card">
                    <div class="card-header">
                        Data Kota/Kabupaten
                        <a href="{{ route('kota.create') }}" class="btn btn-sm btn-primary" style="float: right">
                            Tambah Data
                        </a>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table align-middle" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Kota/Kabupaten</th>
                                      
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach ($kota as $data)
                                        <tr>
                                            <td>{{ $no++ }}</td>
                                            <td>{{ $data->kota }}</td>
                                          
                                            <td>
                                                <form action="{{ route('kota.destroy', $data->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('kota.edit', $data->id) }}" class="btn btn-sm btn-outline-success ">
                                                        <i class='bx bx-edit'></i>
                                                    </a> |
                                                    <a href="{{ route('kota.show', $data->id) }}" class="btn btn-sm btn-outline-warning ">
                                                        <i class='bx bx-show-alt'></i>
                                                    </a> |
                                                    <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Apakah Anda Yakin?')">
                                                        <i class='bx bx-trash'></i>
                                                    </button>
                                                    
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/kota/show.blade.php
@extends('layouts.temadmin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Data Kota/Kabupaten
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label class="form-label">Kota/Kabupaten</label>
                            <input type="text" class="form-control " name="kota" value="{{ $kota->kota }}" readonly>
                        </div>
                      
                     
                                <a href="{{ route('kota.index') }}" class="btn btn-primary" type="submit">Kembali</a>
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection